import type { Opportunity } from "@/types";

/** Curated picks — one strong name per industry, ranked by risk-adjusted quality */
export const DIVERSIFIED_STOCKS: Opportunity[] = [
  {
    id: "stk-banking",
    name: "ICICI Bank",
    symbol: "ICICIBANK.NS",
    type: "stock",
    theme: "Credit Growth",
    sector: "Banking",
    currentPrice: 1285,
    currency: "INR",
    confidenceScore: 84,
    riskScore: 26,
    potentialUpsideMin: 15,
    potentialUpsideMax: 28,
    timeHorizon: "1–2 years",
    whyItMatters: "Leading private bank benefiting from retail credit expansion and improving asset quality.",
    whyNow: ["Credit growth at 15%+ YoY", "NIM stabilizing", "Digital banking share gains"],
    whyCouldFail: ["NPA cycle reversal", "Competitive deposit pricing", "Regulatory caps on unsecured lending"],
    investmentThesis: "Best-in-class private bank with strong ROE and granular retail franchise.",
    bullCase: "Earnings compounding as credit cycle remains supportive.",
    bearCase: "Valuation premium to historical average limits upside.",
    disconfirmingEvidence: ["Unsecured loan growth slowing in recent quarter"],
    beneficiarySectors: ["Banking", "Financial Services"],
  },
  {
    id: "stk-it",
    name: "TCS",
    symbol: "TCS.NS",
    type: "stock",
    theme: "Digital Transformation",
    sector: "IT Services",
    currentPrice: 4120,
    currency: "INR",
    confidenceScore: 80,
    riskScore: 22,
    potentialUpsideMin: 12,
    potentialUpsideMax: 22,
    timeHorizon: "1–3 years",
    whyItMatters: "India's largest IT exporter with resilient margins and strong client relationships.",
    whyNow: ["Deal pipeline improving", "GenAI services gaining traction", "Attrition normalized"],
    whyCouldFail: ["US recession reducing tech spend", "Visa restrictions", "Pricing pressure"],
    investmentThesis: "Quality compounder in IT with best-in-class execution and cash generation.",
    bullCase: "GenAI-led deal wins and margin expansion.",
    bearCase: "Structural slowdown in legacy outsourcing.",
    disconfirmingEvidence: ["Revenue growth below 10% in recent quarters"],
    beneficiarySectors: ["IT Services"],
  },
  {
    id: "stk-pharma",
    name: "Sun Pharmaceutical",
    symbol: "SUNPHARMA.NS",
    type: "stock",
    theme: "Specialty Pharma",
    sector: "Pharma",
    currentPrice: 1785,
    currency: "INR",
    confidenceScore: 78,
    riskScore: 24,
    potentialUpsideMin: 14,
    potentialUpsideMax: 25,
    timeHorizon: "1–2 years",
    whyItMatters: "India's largest pharma company with growing US specialty portfolio.",
    whyNow: ["US specialty launches ramping", "India chronic portfolio strong", "R&D pipeline maturing"],
    whyCouldFail: ["US FDA inspection issues", "Patent cliffs", "Currency headwinds"],
    investmentThesis: "Transition from generics to specialty driving margin expansion.",
    bullCase: "Specialty revenue mix improving profitability.",
    bearCase: "US pricing pressure on generics.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Pharma", "Healthcare"],
  },
  {
    id: "stk-defence",
    name: "Bharat Electronics",
    symbol: "BEL.NS",
    type: "stock",
    theme: "Defence Indigenization",
    sector: "Defence",
    currentPrice: 285,
    currency: "INR",
    confidenceScore: 86,
    riskScore: 30,
    potentialUpsideMin: 20,
    potentialUpsideMax: 35,
    timeHorizon: "2–4 years",
    whyItMatters: "Defence PSU with order book visibility from government's indigenization push.",
    whyNow: ["Defence budget at record highs", "Order book at 2x revenue", "Export opportunities opening"],
    whyCouldFail: ["Order execution delays", "Working capital strain", "Valuation stretched"],
    investmentThesis: "Structural beneficiary of India's defence self-reliance policy.",
    bullCase: "Multi-year order book provides earnings visibility.",
    bearCase: "PSU governance and execution risks.",
    disconfirmingEvidence: ["Order inflow slowed in last quarter"],
    beneficiarySectors: ["Defence", "Aerospace"],
  },
  {
    id: "stk-power",
    name: "NTPC",
    symbol: "NTPC.NS",
    type: "stock",
    theme: "Power Generation",
    sector: "Power",
    currentPrice: 385,
    currency: "INR",
    confidenceScore: 76,
    riskScore: 20,
    potentialUpsideMin: 12,
    potentialUpsideMax: 20,
    timeHorizon: "1–3 years",
    whyItMatters: "India's largest power producer pivoting to renewables while maintaining thermal cash flows.",
    whyNow: ["Renewable capacity targets raised", "Stable dividend yield ~3%", "Regulated returns on thermal"],
    whyCouldFail: ["Renewable transition capex strain", "Coal supply disruptions", "Regulatory tariff revisions"],
    investmentThesis: "Low-risk utility play with renewable growth optionality.",
    bullCase: "Renewable portfolio monetization unlocks value.",
    bearCase: "Thermal plant utilization declining faster than expected.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Power", "Renewables"],
  },
  {
    id: "stk-infra",
    name: "Larsen & Toubro",
    symbol: "LT.NS",
    type: "stock",
    theme: "Infrastructure Capex",
    sector: "Infrastructure",
    currentPrice: 3580,
    currency: "INR",
    confidenceScore: 82,
    riskScore: 28,
    potentialUpsideMin: 18,
    potentialUpsideMax: 30,
    timeHorizon: "1–3 years",
    whyItMatters: "India's premier EPC company with exposure to roads, metros, defence, and hydrocarbon projects.",
    whyNow: ["Order inflow at record levels", "Government capex pipeline strong", "Margin improvement trajectory"],
    whyCouldFail: ["Project execution delays", "Working capital intensity", "Margin compression on competition"],
    investmentThesis: "Proxy for India's infrastructure buildout with diversified revenue streams.",
    bullCase: "Order book provides 2+ years revenue visibility.",
    bearCase: "Cyclical slowdown in private capex.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Infrastructure", "Capital Goods"],
  },
  {
    id: "stk-fmcg",
    name: "ITC",
    symbol: "ITC.NS",
    type: "stock",
    theme: "FMCG Diversification",
    sector: "FMCG",
    currentPrice: 465,
    currency: "INR",
    confidenceScore: 74,
    riskScore: 18,
    potentialUpsideMin: 10,
    potentialUpsideMax: 18,
    timeHorizon: "1–2 years",
    whyItMatters: "Cigarette cash cow funding rapid FMCG and hotel expansion with strong dividend yield.",
    whyNow: ["FMCG revenue growing 15%+", "Hotel segment recovering", "Demerger unlocking value"],
    whyCouldFail: ["Regulatory risk on tobacco", "FMCG competition from D2C brands", "Volume decline in cigarettes"],
    investmentThesis: "Value play with hidden FMCG growth and capital allocation improving.",
    bullCase: "FMCG segment reaching scale profitability.",
    bearCase: "ESG concerns limiting institutional ownership.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["FMCG", "Hotels"],
  },
  {
    id: "stk-auto",
    name: "Maruti Suzuki",
    symbol: "MARUTI.NS",
    type: "stock",
    theme: "Auto Recovery",
    sector: "Auto",
    currentPrice: 12450,
    currency: "INR",
    confidenceScore: 77,
    riskScore: 25,
    potentialUpsideMin: 14,
    potentialUpsideMax: 24,
    timeHorizon: "1–2 years",
    whyItMatters: "Market leader in passenger vehicles with SUV portfolio driving mix improvement.",
    whyNow: ["SUV mix at 55%+ improving margins", "Waiting periods on new launches", "Rural demand recovering"],
    whyCouldFail: ["EV disruption risk", "Intense SUV competition", "Input cost inflation"],
    investmentThesis: "Dominant franchise benefiting from premiumization and export growth.",
    bullCase: "SUV-led margin expansion continues.",
    bearCase: "Market share loss to Hyundai and Tata in SUVs.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Auto"],
  },
  {
    id: "stk-realty",
    name: "DLF",
    symbol: "DLF.NS",
    type: "stock",
    theme: "Premium Housing",
    sector: "Realty",
    currentPrice: 875,
    currency: "INR",
    confidenceScore: 72,
    riskScore: 32,
    potentialUpsideMin: 15,
    potentialUpsideMax: 28,
    timeHorizon: "2–3 years",
    whyItMatters: "Premium real estate developer with strong Gurugram land bank and rental REIT income.",
    whyNow: ["Luxury housing demand at decade highs", "DLF Cyber City rental income growing", "Low leverage balance sheet"],
    whyCouldFail: ["Interest rate sensitivity", "Regulatory changes in real estate", "Premium segment saturation"],
    investmentThesis: "Play on India's premium housing upcycle with annuity rental income.",
    bullCase: "New project launches in premium segments sell out fast.",
    bearCase: "Rate hikes dampen housing demand.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Realty", "Construction"],
  },
  {
    id: "stk-metals",
    name: "Tata Steel",
    symbol: "TATASTEEL.NS",
    type: "stock",
    theme: "Steel Cycle",
    sector: "Metals",
    currentPrice: 158,
    currency: "INR",
    confidenceScore: 70,
    riskScore: 35,
    potentialUpsideMin: 18,
    potentialUpsideMax: 32,
    timeHorizon: "1–2 years",
    whyItMatters: "Integrated steel producer benefiting from infrastructure demand and EU operations turnaround.",
    whyNow: ["India steel demand growing 8%+", "Infrastructure projects driving volumes", "Debt reduction on track"],
    whyCouldFail: ["Global steel oversupply from China", "Coking coal price volatility", "EU operations drag"],
    investmentThesis: "Cyclical play on India's infrastructure steel demand with global diversification.",
    bullCase: "Domestic volume growth with stable realizations.",
    bearCase: "China dumping depressing global prices.",
    disconfirmingEvidence: ["EU segment still loss-making"],
    beneficiarySectors: ["Metals", "Infrastructure"],
  },
  {
    id: "stk-capital-goods",
    name: "Siemens India",
    symbol: "SIEMENS.NS",
    type: "stock",
    theme: "Industrial Automation",
    sector: "Capital Goods",
    currentPrice: 6850,
    currency: "INR",
    confidenceScore: 79,
    riskScore: 27,
    potentialUpsideMin: 16,
    potentialUpsideMax: 26,
    timeHorizon: "1–3 years",
    whyItMatters: "Premium industrial technology company riding factory automation and smart infrastructure trends.",
    whyNow: ["Smart factory adoption accelerating", "Rail and mobility orders strong", "Margin expansion trajectory"],
    whyCouldFail: ["High valuation multiple", "Import competition", "Industrial slowdown"],
    investmentThesis: "Quality industrial franchise with technology moat and pricing power.",
    bullCase: "Automation and digitalization drive premium growth.",
    bearCase: "Capex cycle turns down.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Capital Goods", "Manufacturing"],
  },
  {
    id: "stk-electrical",
    name: "Polycab India",
    symbol: "POLYCAB.NS",
    type: "stock",
    theme: "Electrification",
    sector: "Electrical Equipment",
    currentPrice: 6842,
    currency: "INR",
    confidenceScore: 82,
    riskScore: 28,
    potentialUpsideMin: 20,
    potentialUpsideMax: 35,
    timeHorizon: "1–3 years",
    whyItMatters: "India's largest cable maker benefiting from electrification, data centers, and housing.",
    whyNow: ["Data center cable demand surging", "Housing wire segment gaining share", "Export markets opening"],
    whyCouldFail: ["Copper price volatility", "Competition intensifying", "Valuation premium"],
    investmentThesis: "Market leader in a fragmented industry with secular demand tailwinds.",
    bullCase: "Premium mix and export growth drive margins.",
    bearCase: "Cyclical industrial demand slowdown.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Electrical Equipment", "Data Centers"],
  },
];

export const DIVERSIFIED_FUNDS: Opportunity[] = [
  {
    id: "mf-flexi",
    name: "Parag Parikh Flexi Cap Fund",
    symbol: "122639",
    type: "mutual_fund",
    theme: "Quality Growth",
    sector: "Flexi Cap",
    currentPrice: 82.45,
    currency: "INR",
    confidenceScore: 86,
    riskScore: 20,
    potentialUpsideMin: 12,
    potentialUpsideMax: 18,
    timeHorizon: "3–5 years",
    whyItMatters: "Top-quartile flexi cap fund with global diversification and value discipline.",
    whyNow: ["Consistent long-term outperformance", "Global allocation reduces India risk", "Reasonable valuations"],
    whyCouldFail: ["USD strength hurts international holdings", "Large cap concentration"],
    investmentThesis: "Best-in-class fund house with patient capital approach.",
    bullCase: "Compounding through quality at reasonable prices.",
    bearCase: "Underperformance in momentum markets.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Diversified"],
  },
  {
    id: "mf-largecap",
    name: "Mirae Asset Large Cap Fund",
    symbol: "118825",
    type: "mutual_fund",
    theme: "Blue Chip Stability",
    sector: "Large Cap",
    currentPrice: 112.3,
    currency: "INR",
    confidenceScore: 82,
    riskScore: 18,
    potentialUpsideMin: 10,
    potentialUpsideMax: 16,
    timeHorizon: "3–5 years",
    whyItMatters: "Consistent large cap performer with focus on quality franchises.",
    whyNow: ["Large caps relatively undervalued vs mid/small", "Institutional flows favoring quality"],
    whyCouldFail: ["Index underperformance if small caps rally"],
    investmentThesis: "Core portfolio holding for stable equity exposure.",
    bullCase: "Earnings recovery in Nifty 50 constituents.",
    bearCase: "Style rotation away from large caps.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Large Cap"],
  },
  {
    id: "mf-midcap",
    name: "Kotak Emerging Equity Fund",
    symbol: "100377",
    type: "mutual_fund",
    theme: "Mid Cap Growth",
    sector: "Mid Cap",
    currentPrice: 98.5,
    currency: "INR",
    confidenceScore: 80,
    riskScore: 28,
    potentialUpsideMin: 14,
    potentialUpsideMax: 22,
    timeHorizon: "3–5 years",
    whyItMatters: "Established mid cap fund with strong stock selection track record.",
    whyNow: ["Mid cap earnings growth outpacing large caps", "Domestic economy recovery"],
    whyCouldFail: ["Mid cap valuations elevated", "Liquidity risk in downturns"],
    investmentThesis: "Capture India's mid-cap growth with experienced management.",
    bullCase: "Domestic consumption and capex benefit mid caps.",
    bearCase: "Small/mid cap correction risk.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Mid Cap"],
  },
  {
    id: "mf-smallcap",
    name: "Nippon India Small Cap Fund",
    symbol: "118778",
    type: "mutual_fund",
    theme: "Small Cap Alpha",
    sector: "Small Cap",
    currentPrice: 142.8,
    currency: "INR",
    confidenceScore: 75,
    riskScore: 35,
    potentialUpsideMin: 16,
    potentialUpsideMax: 28,
    timeHorizon: "5+ years",
    whyItMatters: "High-conviction small cap fund for aggressive long-term investors.",
    whyNow: ["Small cap earnings cycle turning up", "Manufacturing PLI beneficiaries in portfolio"],
    whyCouldFail: ["SEBI small cap regulation risk", "Liquidity crunch in sell-offs"],
    investmentThesis: "Long-term wealth creation through undiscovered small companies.",
    bullCase: "India's manufacturing boom lifts small caps.",
    bearCase: "Valuations at historical highs.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Small Cap"],
  },
  {
    id: "mf-index",
    name: "UTI Nifty 50 Index Fund",
    symbol: "120716",
    type: "mutual_fund",
    theme: "Passive Investing",
    sector: "Index Fund",
    currentPrice: 168.2,
    currency: "INR",
    confidenceScore: 78,
    riskScore: 15,
    potentialUpsideMin: 10,
    potentialUpsideMax: 15,
    timeHorizon: "5+ years",
    whyItMatters: "Low-cost index fund tracking India's top 50 companies.",
    whyNow: ["Lowest expense ratio in category", "Passive investing gaining adoption"],
    whyCouldFail: ["No alpha generation", "Concentrated in few large names"],
    investmentThesis: "Simple, low-cost market exposure for core portfolio.",
    bullCase: "India GDP growth drives index returns.",
    bearCase: "Active funds outperform in stock-picker's market.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Index"],
  },
  {
    id: "mf-gold",
    name: "SBI Gold ETF",
    symbol: "115585",
    type: "mutual_fund",
    theme: "Gold Hedge",
    sector: "Gold ETF",
    currentPrice: 68.5,
    currency: "INR",
    confidenceScore: 72,
    riskScore: 12,
    potentialUpsideMin: 8,
    potentialUpsideMax: 15,
    timeHorizon: "3–5 years",
    whyItMatters: "Portfolio hedge against inflation and geopolitical uncertainty.",
    whyNow: ["Gold at support levels", "Central bank buying globally", "Rupee depreciation hedge"],
    whyCouldFail: ["Real rates rising", "USD strength", "Risk-on sentiment"],
    investmentThesis: "5-10% gold allocation reduces portfolio volatility.",
    bullCase: "Geopolitical tensions support gold prices.",
    bearCase: "Equity rally reduces safe-haven demand.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Gold"],
  },
  {
    id: "mf-international",
    name: "Motilal Oswal Nasdaq 100 FOF",
    symbol: "149030",
    type: "mutual_fund",
    theme: "US Tech Exposure",
    sector: "International",
    currentPrice: 42.8,
    currency: "INR",
    confidenceScore: 74,
    riskScore: 30,
    potentialUpsideMin: 12,
    potentialUpsideMax: 22,
    timeHorizon: "3–5 years",
    whyItMatters: "Access to US tech giants (Apple, Microsoft, Nvidia) through Indian mutual fund.",
    whyNow: ["AI revolution driven by US tech", "Rupee diversification benefit"],
    whyCouldFail: ["USD-INR currency risk", "US recession", "Tech valuation correction"],
    investmentThesis: "Geographic diversification into world's leading technology companies.",
    bullCase: "AI capex cycle benefits Nasdaq constituents.",
    bearCase: "US rate hikes compress tech multiples.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["International", "Technology"],
  },
  {
    id: "mf-banking",
    name: "ICICI Pru Banking & Financial Services",
    symbol: "120594",
    type: "mutual_fund",
    theme: "Financial Sector",
    sector: "Sectoral - Banking",
    currentPrice: 22.5,
    currency: "INR",
    confidenceScore: 76,
    riskScore: 26,
    potentialUpsideMin: 12,
    potentialUpsideMax: 20,
    timeHorizon: "2–3 years",
    whyItMatters: "Sectoral bet on India's financial services growth including banks, NBFCs, and insurance.",
    whyNow: ["Credit growth cycle intact", "Financial inclusion expanding", "Insurance penetration low"],
    whyCouldFail: ["Credit cycle downturn", "NBFC liquidity issues", "Regulatory changes"],
    investmentThesis: "India's credit-to-GDP ratio has room to grow vs developed markets.",
    bullCase: "Rate cut cycle boosts financial sector earnings.",
    bearCase: "Rising NPAs in unsecured lending.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Banking", "NBFC"],
  },
  {
    id: "mf-hybrid",
    name: "ICICI Pru Balanced Advantage Fund",
    symbol: "120364",
    type: "mutual_fund",
    theme: "Dynamic Asset Allocation",
    sector: "Hybrid",
    currentPrice: 72.4,
    currency: "INR",
    confidenceScore: 80,
    riskScore: 16,
    potentialUpsideMin: 9,
    potentialUpsideMax: 14,
    timeHorizon: "3–5 years",
    whyItMatters: "Automatically adjusts equity-debt mix based on market valuations — lower risk.",
    whyNow: ["Equity valuations elevated — fund reducing equity exposure", "Lower volatility than pure equity"],
    whyCouldFail: ["Underperforms in strong bull markets", "Complex allocation strategy"],
    investmentThesis: "Ideal for moderate risk investors wanting equity exposure with downside protection.",
    bullCase: "Dynamic allocation protects in corrections.",
    bearCase: "Misses full upside in raging bull market.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["Hybrid"],
  },
  {
    id: "mf-elss",
    name: "Axis Long Term Equity Fund",
    symbol: "120503",
    type: "mutual_fund",
    theme: "Tax Saving",
    sector: "ELSS",
    currentPrice: 88.6,
    currency: "INR",
    confidenceScore: 78,
    riskScore: 24,
    potentialUpsideMin: 11,
    potentialUpsideMax: 17,
    timeHorizon: "3+ years (lock-in)",
    whyItMatters: "ELSS fund offering Section 80C tax deduction with equity growth potential.",
    whyNow: ["Tax-saving season approaching", "Consistent ELSS category performer"],
    whyCouldFail: ["3-year lock-in limits liquidity", "Mid cap tilt increases volatility"],
    investmentThesis: "Tax-efficient equity investing for salaried professionals.",
    bullCase: "Tax saving + equity compounding.",
    bearCase: "Lock-in period traps capital in downturn.",
    disconfirmingEvidence: [],
    beneficiarySectors: ["ELSS", "Tax Saving"],
  },
];

export function calcRiskAdjustedReturn(opp: Opportunity): number {
  const upsideMid = (opp.potentialUpsideMin + opp.potentialUpsideMax) / 2;
  return Math.round((upsideMid / Math.max(opp.riskScore, 1)) * 10) / 10;
}

/** Pick top N opportunities with at most one per sector/category */
export function pickDiversified(
  pool: Opportunity[],
  count: number,
  groupBy: "sector" | "theme" = "sector"
): Opportunity[] {
  const sorted = [...pool].sort(
    (a, b) => calcRiskAdjustedReturn(b) - calcRiskAdjustedReturn(a)
  );

  const seen = new Set<string>();
  const result: Opportunity[] = [];

  for (const opp of sorted) {
    const key = groupBy === "sector" ? opp.sector : opp.theme;
    if (seen.has(key)) continue;
    seen.add(key);
    result.push(opp);
    if (result.length >= count) break;
  }

  // Fill remaining slots if we have fewer sectors than count
  if (result.length < count) {
    for (const opp of sorted) {
      if (result.find((r) => r.id === opp.id)) continue;
      result.push(opp);
      if (result.length >= count) break;
    }
  }

  return result;
}

/** Daily stock picks: 10 stocks from 10 different industries */
export function getDailyStockPicks(extraOpportunities: Opportunity[] = []): Opportunity[] {
  const merged = [...DIVERSIFIED_STOCKS];
  for (const opp of extraOpportunities) {
    if (opp.type !== "stock") continue;
    if (!merged.find((m) => m.sector === opp.sector)) {
      merged.push(opp);
    }
  }
  return pickDiversified(merged, 10, "sector");
}

/** Daily fund picks: 10 funds from different categories */
export function getDailyFundPicks(extraOpportunities: Opportunity[] = []): Opportunity[] {
  const merged = [...DIVERSIFIED_FUNDS];
  for (const opp of extraOpportunities) {
    if (opp.type !== "mutual_fund") continue;
    if (!merged.find((m) => m.sector === opp.sector)) {
      merged.push(opp);
    }
  }
  return pickDiversified(merged, 10, "sector");
}

/** Combined daily recommendations */
export function getDiversifiedOpportunities(aiOpportunities: Opportunity[] = []): Opportunity[] {
  const stocks = getDailyStockPicks(aiOpportunities);
  const funds = getDailyFundPicks(aiOpportunities);
  return [...stocks, ...funds];
}
