import type { UpcomingIpo } from "@/types/ipo";

export const UPCOMING_IPOS: UpcomingIpo[] = [
  {
    id: "ipo-1",
    companyName: "Hexaware Technologies",
    sector: "IT Services",
    status: "Upcoming",
    expectedOpenDate: "Jun 2026",
    priceBandMin: 750,
    priceBandMax: 775,
    issueSizeCr: 8750,
    lotSize: 19,
    leadManagers: ["Kotak Mahindra Capital", "JM Financial"],
    businessSummary:
      "Global IT services company with $1.3B revenue, strong in cloud, automation, and digital engineering. PE-backed (Baring) seeking partial exit via IPO.",
    honestTake:
      "A mature, profitable IT company — not a typical high-growth IPO story. The issue is primarily an exit for PE investors. At 25-27x earnings, valuation is fair but not cheap. Good business, mediocre IPO opportunity unless priced at lower end of band.",
    verdict: "Neutral",
    worthInvesting: false,
    upsideMin: 8,
    upsideMax: 18,
    downsideMin: 10,
    downsideMax: 20,
    riskScore: 35,
    confidenceScore: 62,
    listingGainPotential: "Low to moderate — large issue size (₹8,750 Cr) limits listing pop",
    longTermPotential: "Moderate — steady 12-15% earnings growth, but limited re-rating upside as a mature IT name",
    bullCase: "Strong cash flows, dividend paying, cloud revenue growing 25%+. Brand recognition in mid-tier IT.",
    bearCase: "PE exit overhang, US client concentration, mature business with limited growth vs smaller IT peers.",
    whySubscribe: ["Quality IT business with proven track record", "If priced at lower band (₹750)"],
    whyAvoid: [
      "Primary issue is PE exit — not growth capital",
      "Large issue size will absorb demand",
      "Better IT opportunities exist in secondary market (Persistent, Coforge)",
    ],
    greyMarketPremium: 5,
    peerComparison: "Trades in line with Mphasis and Coforge — no discount for IPO investors",
  },
  {
    id: "ipo-2",
    companyName: "LG Electronics India",
    sector: "Consumer Durables",
    status: "Upcoming",
    expectedOpenDate: "Jul 2026",
    priceBandMin: 1140,
    priceBandMax: 1180,
    issueSizeCr: 11500,
    lotSize: 12,
    leadManagers: ["Goldman Sachs", "JPMorgan", "Citigroup"],
    businessSummary:
      "Indian subsidiary of LG Corp — manufactures TVs, washing machines, refrigerators, and ACs. Market leader in premium appliances with 20%+ revenue growth.",
    honestTake:
      "India's consumer durables boom is real, and LG is a genuine market leader. But ₹11,500 Cr is the largest consumer IPO ever — the parent is exiting, not investing. At 55-60x P/E, you're paying a massive premium for a brand name. Listing gains possible due to hype, but long-term investors should wait for a correction.",
    verdict: "Listing Gains Only",
    worthInvesting: false,
    upsideMin: 10,
    upsideMax: 25,
    downsideMin: 15,
    downsideMax: 30,
    riskScore: 42,
    confidenceScore: 58,
    listingGainPotential: "Moderate to high — brand hype and consumer theme could drive 15-20% listing pop",
    longTermPotential: "Low at issue price — valuation leaves no margin of safety for 3+ year holding",
    bullCase: "India AC and premium appliance penetration still low. LG brand commands premium. Revenue growing 20%+.",
    bearCase: "Parent selling entire stake — no skin in the game. Extreme valuation. Competition from Samsung, Voltas, and Chinese brands.",
    whySubscribe: ["If you want quick listing gains and can sell on listing day", "Strong brand with consumer tailwinds"],
    whyAvoid: [
      "Valuation is among the most expensive consumer IPOs ever",
      "Parent exit — zero alignment with public shareholders",
      "Buy Voltas or Blue Star in secondary market for better value",
    ],
    greyMarketPremium: 12,
    peerComparison: "Voltas trades at 65x P/E but growing faster — LG premium not justified for long term",
  },
  {
    id: "ipo-3",
    companyName: "National Stock Exchange (NSE)",
    sector: "Financial Services",
    status: "Upcoming",
    expectedOpenDate: "H2 2026",
    priceBandMin: 0,
    priceBandMax: 0,
    issueSizeCr: 10000,
    leadManagers: ["To be announced"],
    businessSummary:
      "India's largest stock exchange — near-monopoly in equity derivatives (99%+ market share). One of the most profitable financial institutions in India with 50%+ net margins.",
    honestTake:
      "The most anticipated IPO in Indian capital markets history. NSE is a money-printing monopoly — but regulatory risk is real (SEBI has penalized NSE before). Pricing will be critical. If valued above 40x earnings, avoid. Below 30x, this is a generational wealth creation opportunity. Wait for price band before deciding.",
    verdict: "Neutral",
    worthInvesting: false,
    upsideMin: 15,
    upsideMax: 40,
    downsideMin: 10,
    downsideMax: 25,
    riskScore: 30,
    confidenceScore: 75,
    listingGainPotential: "High if priced reasonably — massive investor demand expected",
    longTermPotential: "Very high if priced right — monopoly business with 50%+ margins and FMCG-like cash flows",
    bullCase: "Near-monopoly exchange with derivatives cash cow. India's capital markets growing 20%+ annually. Zero competition risk.",
    bearCase: "Regulatory risk (SEBI can cap fees), colocation scandal history, pricing likely to be aggressive given hype.",
    whySubscribe: ["If P/E below 30x — generational compounder", "Monopoly business with pricing power"],
    whyAvoid: ["If P/E above 40x — hype premium not justified", "Regulatory overhang from SEBI"],
    peerComparison: "BSE trades at 55x — NSE deserves premium but not unlimited",
  },
  {
    id: "ipo-4",
    companyName: "Shadowfax",
    sector: "Logistics",
    status: "Upcoming",
    expectedOpenDate: "Jun 2026",
    priceBandMin: 95,
    priceBandMax: 102,
    issueSizeCr: 1800,
    lotSize: 147,
    leadManagers: ["Axis Capital", "ICICI Securities"],
    businessSummary:
      "Last-mile logistics platform for e-commerce and quick commerce — India's largest hyperlocal delivery network with 1M+ delivery partners.",
    honestTake:
      "Logistics is the backbone of India's e-commerce boom, but last-mile delivery is brutally competitive and low-margin. Shadowfax is growing fast (40%+ revenue growth) but still loss-making. This is a bet on quick commerce (Blinkit, Zepto) continuing to grow. High risk, high reward — only for aggressive investors who understand the unit economics.",
    verdict: "Avoid",
    worthInvesting: false,
    upsideMin: 15,
    upsideMax: 35,
    downsideMin: 25,
    downsideMax: 45,
    riskScore: 68,
    confidenceScore: 45,
    listingGainPotential: "Unpredictable — logistics IPOs have mixed track record (Delhivery fell 40% post-listing)",
    longTermPotential: "Uncertain — depends entirely on quick commerce profitability timeline",
    bullCase: "Quick commerce growing 100%+ YoY. Largest hyperlocal network. Path to profitability by FY27.",
    bearCase: "Still loss-making. Delhivery down 50% from listing. Competition from Dunzo, Porter, and in-house delivery.",
    whySubscribe: ["If you believe quick commerce is India's next mega-trend"],
    whyAvoid: [
      "Loss-making with uncertain path to profitability",
      "Delhivery IPO destroyed shareholder wealth",
      "Delivery partner costs rising, margins under pressure",
      "Better logistics exposure via CONCOR in secondary market",
    ],
    greyMarketPremium: -3,
    peerComparison: "Delhivery trades at 1.5x revenue — Shadowfax likely similar, no bargain",
  },
  {
    id: "ipo-5",
    companyName: "SME IPO — Awligic",
    sector: "Manufacturing",
    status: "Upcoming",
    expectedOpenDate: "May 2026",
    priceBandMin: 55,
    priceBandMax: 58,
    issueSizeCr: 45,
    lotSize: 200,
    leadManagers: ["Pantomath Capital"],
    businessSummary:
      "Small manufacturing company in automotive components — supplies to tier-1 auto OEMs with ₹120 Cr annual revenue.",
    honestTake:
      "Typical SME IPO — small company, limited track record as public entity, low liquidity post-listing. SME IPOs have a terrible track record in India with 60%+ trading below issue price within a year. The only reason to subscribe is for listing gains (which can be 30-50% on SME exchanges), but never hold long term.",
    verdict: "Listing Gains Only",
    worthInvesting: false,
    upsideMin: 20,
    upsideMax: 50,
    downsideMin: 30,
    downsideMax: 60,
    riskScore: 75,
    confidenceScore: 35,
    listingGainPotential: "High on listing day — SME IPOs often pop 30-50% due to low float",
    longTermPotential: "Very poor — most SME IPOs destroy wealth after initial pop",
    bullCase: "Auto component demand growing. Small issue size means low float pop.",
    bearCase: "SME IPO graveyard is vast. Low liquidity trap. No institutional coverage.",
    whySubscribe: ["Only for listing day trading with strict stop-loss"],
    whyAvoid: [
      "Never hold SME IPOs long term — data shows 60%+ underperform",
      "No institutional research coverage",
      "Liquidity dries up after listing",
    ],
    peerComparison: "No meaningful peers — too small for comparison",
  },
  {
    id: "ipo-6",
    companyName: "Tata Capital",
    sector: "NBFC / Financial Services",
    status: "Upcoming",
    expectedOpenDate: "Q3 2026",
    priceBandMin: 0,
    priceBandMax: 0,
    issueSizeCr: 15000,
    leadManagers: ["To be announced"],
    businessSummary:
      "Tata Group's NBFC arm — consumer loans, business lending, wealth management, and insurance distribution. ₹1.5 lakh Cr+ AUM with Tata brand backing.",
    honestTake:
      "Tata brand is gold, and the NBFC business is solid with 3%+ ROA. But ₹15,000 Cr issue size is enormous, and NBFC sector is under regulatory scrutiny after recent incidents. Bajaj Finance trades at 6x book — if Tata Capital prices similarly, it's fair but not exciting. Tata brand premium may drive listing pop, but long-term returns depend entirely on pricing.",
    verdict: "Neutral",
    worthInvesting: false,
    upsideMin: 10,
    upsideMax: 22,
    downsideMin: 12,
    downsideMax: 25,
    riskScore: 40,
    confidenceScore: 65,
    listingGainPotential: "Moderate — Tata brand commands loyalty from retail investors",
    longTermPotential: "Good if priced below Bajaj Finance — Tata brand + diversified lending book",
    bullCase: "Tata trust factor. Diversified NBFC with consumer, SME, and wealth. Strong parent backing.",
    bearCase: "NBFC sector risk. Large issue size. RBI regulatory tightening on unsecured lending.",
    whySubscribe: ["If priced at discount to Bajaj Finance", "Tata brand long-term compounder"],
    whyAvoid: ["If priced at premium to Bajaj Finance", "NBFC sector headwinds from RBI"],
    peerComparison: "Bajaj Finance at 6x book, Cholamandalam at 4x — Tata should price between these",
  },
  {
    id: "ipo-7",
    companyName: "PhysicsWallah",
    sector: "EdTech",
    status: "Upcoming",
    expectedOpenDate: "H2 2026",
    priceBandMin: 0,
    priceBandMax: 0,
    issueSizeCr: 3500,
    leadManagers: ["To be announced"],
    businessSummary:
      "India's fastest-growing EdTech company — YouTube-to-unicorn story. 5M+ paid students, profitable (unlike Byju's), focused on affordable test prep for JEE, NEET, and UPSC.",
    honestTake:
      "The anti-Byju's. PhysicsWallah is actually profitable, founder-led, and focused on affordable education — a genuine social impact story. Revenue growing 80%+ with positive unit economics. This could be the EdTech IPO that works. Key risk: can they maintain growth as they move from YouTube-free to paid app? If priced below 15x revenue, genuinely interesting.",
    verdict: "Subscribe",
    worthInvesting: true,
    upsideMin: 20,
    upsideMax: 45,
    downsideMin: 15,
    downsideMax: 30,
    riskScore: 48,
    confidenceScore: 72,
    listingGainPotential: "High — EdTech revival narrative + profitable growth story",
    longTermPotential: "High if they maintain 50%+ growth — India's test prep market is massive and underpenetrated",
    bullCase: "Profitable EdTech (rare). Founder Alakh Pandey is the brand. 5M students at ₹3,500 ARPU with room to grow.",
    bearCase: "EdTech sentiment destroyed by Byju's collapse. Free YouTube content competes with paid app. Scaling beyond test prep unproven.",
    whySubscribe: [
      "Rare profitable EdTech with genuine moat (teacher brand)",
      "Affordable education taps India's mass market",
      "Founder-led with skin in the game",
    ],
    whyAvoid: [
      "EdTech sector stigma after Byju's",
      "Growth may slow as base grows",
      "Competition from Unacademy and free content",
    ],
    greyMarketPremium: 18,
    peerComparison: "No listed Indian EdTech peer — first profitable one could re-rate the sector",
  },
  {
    id: "ipo-8",
    companyName: "Schloss Bangalore",
    sector: "Real Estate",
    status: "Upcoming",
    expectedOpenDate: "Jun 2026",
    priceBandMin: 420,
    priceBandMax: 445,
    issueSizeCr: 3200,
    lotSize: 33,
    leadManagers: ["Morgan Stanley", "CLSA"],
    businessSummary:
      "Premium residential developer in Bangalore by Embassy Group — luxury apartments targeting IT professionals and HNIs in Whitefield and North Bangalore.",
    honestTake:
      "Bangalore real estate is booming, and Embassy is a credible developer. But real estate IPOs in India have a mixed track record — Prestige and Brigade have done well, but many others trade below issue price. At 3x book value, you're paying for premium positioning. Decent business, fair price — subscribe only if you believe Bangalore luxury housing has 3+ more years of upcycle.",
    verdict: "Neutral",
    worthInvesting: false,
    upsideMin: 10,
    upsideMax: 22,
    downsideMin: 18,
    downsideMax: 35,
    riskScore: 52,
    confidenceScore: 55,
    listingGainPotential: "Moderate — real estate sentiment is positive with rate cut hopes",
    longTermPotential: "Moderate — Bangalore IT corridor growth supports demand, but cyclical",
    bullCase: "Bangalore housing shortage. IT salary growth driving premium demand. Embassy brand quality.",
    bearCase: "Real estate is cyclical. Interest rate sensitivity. Inventory risk if slowdown hits.",
    whySubscribe: ["If bullish on Bangalore real estate for 3+ years"],
    whyAvoid: [
      "Cyclical sector — timing risk is high",
      "Better real estate exposure via Prestige or Brigade in secondary market",
      "3x book is not cheap for a developer",
    ],
    peerComparison: "Prestige Estates at 3.5x book — fairly valued vs peers",
  },
];

export function getUpcomingIpos(): UpcomingIpo[] {
  return UPCOMING_IPOS;
}
