export const NIFTY_50: { symbol: string; name: string; marketCap: number }[] = [
  { symbol: "RELIANCE.NS", name: "Reliance", marketCap: 1950000 },
  { symbol: "TCS.NS", name: "TCS", marketCap: 1450000 },
  { symbol: "HDFCBANK.NS", name: "HDFC Bank", marketCap: 1200000 },
  { symbol: "BHARTIARTL.NS", name: "Bharti Airtel", marketCap: 950000 },
  { symbol: "ICICIBANK.NS", name: "ICICI Bank", marketCap: 900000 },
  { symbol: "INFY.NS", name: "Infosys", marketCap: 780000 },
  { symbol: "SBIN.NS", name: "SBI", marketCap: 750000 },
  { symbol: "LICI.NS", name: "LIC", marketCap: 620000 },
  { symbol: "ITC.NS", name: "ITC", marketCap: 580000 },
  { symbol: "HINDUNILVR.NS", name: "HUL", marketCap: 560000 },
  { symbol: "LT.NS", name: "L&T", marketCap: 520000 },
  { symbol: "BAJFINANCE.NS", name: "Bajaj Finance", marketCap: 480000 },
  { symbol: "HCLTECH.NS", name: "HCL Tech", marketCap: 450000 },
  { symbol: "MARUTI.NS", name: "Maruti", marketCap: 420000 },
  { symbol: "SUNPHARMA.NS", name: "Sun Pharma", marketCap: 400000 },
  { symbol: "AXISBANK.NS", name: "Axis Bank", marketCap: 380000 },
  { symbol: "KOTAKBANK.NS", name: "Kotak Bank", marketCap: 370000 },
  { symbol: "TITAN.NS", name: "Titan", marketCap: 350000 },
  { symbol: "ULTRACEMCO.NS", name: "UltraTech", marketCap: 340000 },
  { symbol: "NTPC.NS", name: "NTPC", marketCap: 330000 },
  { symbol: "BAJAJFINSV.NS", name: "Bajaj Finserv", marketCap: 320000 },
  { symbol: "ONGC.NS", name: "ONGC", marketCap: 310000 },
  { symbol: "ADANIENT.NS", name: "Adani Ent", marketCap: 300000 },
  { symbol: "WIPRO.NS", name: "Wipro", marketCap: 250000 },
  { symbol: "POWERGRID.NS", name: "Power Grid", marketCap: 240000 },
  { symbol: "M&M.NS", name: "M&M", marketCap: 230000 },
  { symbol: "TATAMOTORS.NS", name: "Tata Motors", marketCap: 220000 },
  { symbol: "HAL.NS", name: "HAL", marketCap: 210000 },
  { symbol: "ADANIPORTS.NS", name: "Adani Ports", marketCap: 200000 },
  { symbol: "COALINDIA.NS", name: "Coal India", marketCap: 195000 },
  { symbol: "TATASTEEL.NS", name: "Tata Steel", marketCap: 190000 },
  { symbol: "ASIANPAINT.NS", name: "Asian Paints", marketCap: 185000 },
  { symbol: "JSWSTEEL.NS", name: "JSW Steel", marketCap: 180000 },
  { symbol: "TECHM.NS", name: "Tech Mahindra", marketCap: 175000 },
  { symbol: "NESTLEIND.NS", name: "Nestle", marketCap: 170000 },
  { symbol: "INDUSINDBK.NS", name: "IndusInd Bank", marketCap: 165000 },
  { symbol: "GRASIM.NS", name: "Grasim", marketCap: 160000 },
  { symbol: "HINDALCO.NS", name: "Hindalco", marketCap: 155000 },
  { symbol: "CIPLA.NS", name: "Cipla", marketCap: 150000 },
  { symbol: "DRREDDY.NS", name: "Dr Reddy's", marketCap: 105000 },
  { symbol: "EICHERMOT.NS", name: "Eicher", marketCap: 100000 },
  { symbol: "APOLLOHOSP.NS", name: "Apollo Hospital", marketCap: 95000 },
  { symbol: "SBILIFE.NS", name: "SBI Life", marketCap: 90000 },
  { symbol: "BPCL.NS", name: "BPCL", marketCap: 85000 },
  { symbol: "TRENT.NS", name: "Trent", marketCap: 80000 },
  { symbol: "HEROMOTOCO.NS", name: "Hero MotoCorp", marketCap: 75000 },
  { symbol: "BRITANNIA.NS", name: "Britannia", marketCap: 70000 },
  { symbol: "DIVISLAB.NS", name: "Divi's Labs", marketCap: 65000 },
  { symbol: "SHRIRAMFIN.NS", name: "Shriram Finance", marketCap: 60000 },
  { symbol: "BAJAJ-AUTO.NS", name: "Bajaj Auto", marketCap: 55000 },
];

export const SECTORS = [
  "Banking",
  "IT",
  "Pharma",
  "Defence",
  "Power",
  "Infrastructure",
  "Capital Goods",
  "FMCG",
  "Auto",
  "Realty",
] as const;

export const THEMES = [
  "AI",
  "Defence",
  "Railways",
  "Power",
  "Semiconductors",
  "Manufacturing",
  "Renewables",
  "EV",
  "Data Centers",
] as const;
